services:
  postgres:
    image: postgres:alpine
    container_name: django-master
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: django-master
      POSTGRES_PASSWORD: django-master

volumes:
  postgres-data: